theme: jekyll-theme-minimal
title: Jeel's homepage
collections:
  projects:
    output: true
    permalink: /projects/:name/
description: >
  Here's a list of my projects:
  {% for project in site.projects %}
    - [{{ project.title }}]({{ project.link }}): {{ project.content | strip_html | strip_newlines | truncate: 160 }}
  {% endfor %}

