theme: jekyll-theme-minimal
title: Jeel's homepage
collections:
  projects:
    output: true
    permalink: /projects/:name/
description: Most repositories will be private, please drop an email for access (jdshah@andrew.cmu.edu)

