theme: jekyll-theme-minimal
title: Jeel's homepage
description: Links to projects 
navbar-links:
  Projects: "projects"
  Resources:
    - Scientific Entity Recognition: "https://github.com/jeeldshah/Scientic_Named_Entity_Recognition"
    - 
